use serde::Serialize;
#[derive(Debug, Serialize, Clone)]
pub enum Lang {
    ZHHANS,
    ZHHANT,
    ENGLISH,
    GERMAN,
    SPANISH,
    FRENCH,
    ITALIAN,
    JAPANESE,
    KOREAN,
    RUSSIAN,
    HINDI,
    THAI,
    AR,
    PT,
    BN,
    MS,
    NL,
    EL,
    LA,
    SV,
    ID,
    PL,
    TR,
    CS,
    ET,
    VI,
    FIL,
    FI,
    HE,
    IS,
    NB,
}

impl From<Lang> for String {
    fn from(val: Lang) -> Self {
        use Lang::*;
        match val {
            ZHHANS => "zh-hans",
            ZHHANT => "zh-hant",
            ENGLISH => "en",
            GERMAN => "de",
            SPANISH => "es",
            FRENCH => "fr",
            ITALIAN => "it",
            JAPANESE => "ja",
            KOREAN => "ko",
            RUSSIAN => "ru",
            HINDI => "hi",
            THAI => "th",
            AR => "ar",
            PT => "pt",
            BN => "bn",
            MS => "ms",
            NL => "nl",
            EL => "el",
            LA => "la",
            SV => "sv",
            ID => "id",
            PL => "pl",
            TR => "tr",
            CS => "cs",
            ET => "et",
            VI => "vi",
            FIL => "fil",
            FI => "fi",
            HE => "he",
            IS => "is",
            NB => "nb",
        }
        .to_string()
    }
}
